name: 'Lintor'
description: 'Run linting on chosen language according to Cloud Factory best practices'

inputs:
  directory:
    description: 'Directory containing SQL files to lint'
    required: true
    default: 'dir/'

  language:
    description: 'Programing language to lint. Possible choice are: SQL, Python'
    required: true

  dialect:
    description: 'SQL dialect to use for linting'
    required: false

  config:
    description: 'Path to SQLFluff configuration file'
    required: true
    default: './../action-repo/config/'

  stop_on_fail:
    description: 'Stop workflow on linting failure'
    required: true
    default: true

runs:
  using: 'composite'
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        path: 'main-repo'

    - name: Checkout GitHub Action repository
      uses: actions/checkout@v4
      with:
        repository: AlexanderJacquot/lintor-actions
        path: 'action-repo'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Validate Language Input
      run: |
        language="${{ inputs.language }}"
        if [[ "$language" != "SQL" && "$language" != "Python" ]]; then
            echo "Error: Unsupported language $language. Only 'SQL' or 'Python' are allowed."
            exit 1
        fi
      shell: bash

    - name: Setup Environment
      run: echo "Setting up for ${{ inputs.language }}"
      shell: bash

    - name: Lint SQL
      if: ${{ inputs.language == 'SQL' }}
      run: |
        echo "Linting SQL with dialect ${{ inputs.dialect || 'default' }}"
        pip install sqlfluff==3.0.1
        sqlfluff lint ${{ inputs.directory }} --dialect ${{ inputs.dialect }} --config ${{ inputs.config }}.sqlfluff ||
        if [ ${{ inputs.stop_on_fail }} == true ]; then
          exit 1
        fi
      shell: bash
      working-directory: ./main-repo

    - name: Lint Python
      if: ${{ inputs.language == 'Python' }}
      run: |
        echo "Linting Python"
        pip install flake8==7.0.0
        python3 -m flake8 './app' --config ${{ inputs.config }}.flake8 ||
        if [ ${{ inputs.stop_on_fail }} == true ]; then
          exit 1
        fi
      shell: bash
      working-directory: ./main-repo